version: '3.8'

services:
  # PostgreSQL Database (for production)
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: weaveviz
      POSTGRES_USER: weaveviz
      POSTGRES_PASSWORD: weaveviz_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U weaveviz"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Redis Cache (optional)
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  # Backend API
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      NODE_ENV: production
      PORT: 4000
      DATABASE_URL: postgresql://weaveviz:weaveviz_password@db:5432/weaveviz
      JWT_SECRET: your-production-jwt-secret-change-this
      UPLOAD_DIR: /app/uploads
      TZ: Asia/Kuala_Lumpur
    volumes:
      - uploads_data:/app/uploads
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Frontend Web App
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    environment:
      VITE_API_BASE: http://localhost:4000/api
    ports:
      - "3000:80"
    depends_on:
      api:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data:
  uploads_data:
